<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>GXW3Boost.Core</AssemblyName>
    <RootNamespace>GXW3Boost.Core</RootNamespace>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <Product>GXW3Boost</Product>
    <Company>mokouliszt</Company>
    <Copyright>Copyright © mokouliszt</Copyright>
  </PropertyGroup>
</Project>
